# -*- coding: utf-8 -*-
"""Aerofit:Business case

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQ26DPg8--MnCKMlhyCq_59JfuGJcb2X
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!gdown https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/001/125/original/aerofit_treadmill.csv?1639992749

df = pd.read_csv('aerofit_treadmill.csv')

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.dtypes

df.describe(include = "all")

df.describe(include = "object").T

df['Gender'].value_counts()

df['Product'].value_counts()

df['MaritalStatus'].value_counts()

df.nunique()

df['Product'].unique()

df['Gender'].unique()

df['MaritalStatus'].unique()

sns.distplot(df['Age'])

sns.distplot(df['Education'], kde = True)

sns.histplot(df['Education'])

sns.histplot(df['Fitness'])

sns.histplot(x = 'Income',data=df,kde=True,hue='Gender')

sns.histplot(df['Usage'],kde=True)

fig, axs=plt.subplots(nrows=1,ncols=3, figsize=(15,5))
sns.countplot(x='Gender',data=df,ax=axs[0], palette='coolwarm')
sns.countplot(x= 'MaritalStatus',data=df,ax=axs[1],palette='plasma')
sns.countplot(x='Product',data= df,ax=axs[2],palette='Set1')


axs[0].set_title('Product Count')
axs[1].set_title('Gender Count')
axs[2].set_title('MaritalStatus Count')

plt.show()
plt.tight_layout()

"""

*   Observation

*   Product Count (actually showing Gender distribution)

Male count is higher (≈105).

Female count is lower (≈75).
👉 This means your dataset has more male customers than female customers.

Gender Count (actually showing Marital Status distribution)

Partnered individuals are higher (≈107).

Single individuals are fewer (≈73).
👉 So, most customers are partnered rather than single.

Marital Status Count (actually showing Product distribution)

Product KP281 has the highest count (≈80).

Product KP481 is next (≈60).

Product KP781 is the lowest (≈40).
👉 Meaning, KP281 is the most popular product, while KP781 is the least popular.

"""

sns.countplot(data=df,x='MaritalStatus',hue='Product')

sns.countplot(data=df, y='Usage',hue='Product')

sns.histplot(data=df, x='Miles',hue='Product',bins=7)

fig, axis = plt.subplots(nrows=3, ncols=2, figsize=(10,5))
fig.subplots_adjust(top=1.1)

sns.boxplot(data=df, x='Age', orient='h', ax=axis[0,0])
sns.boxplot(data=df, x='Education', orient='h', ax=axis[0,1])
sns.boxplot(data=df, x='Fitness', orient='h', ax=axis[1,0])
sns.boxplot(data=df, x='Income', orient='h', ax=axis[1,1])
sns.boxplot(data=df, x='Usage', orient='h', ax=axis[2,0])
sns.boxplot(data=df, x='Miles', orient='h', ax=axis[2,1])
plt.show()

"""📊 Observations from the Boxplots
Left Column (Usage & another variable)

Top-left (Variable ~20–50 range, maybe Age or similar)

Median ≈ 26–28.

Most values lie between 20 and 35.

A few outliers above 45–50.
👉 Data is slightly right-skewed with high-value outliers.

Middle-left (Usage 1–5)

Median ≈ 3.

Data is fairly symmetric.

One very low outlier (≈1).
👉 Most users fall in the 2–4 range.

Bottom-left (Usage 2–7)

Median ≈ 3–3.5.

Majority of data in 3–5.

Some high outliers above 6.
👉 A few heavy users compared to the majority.

Right Column (Miles)

Top-right (12–21 range, maybe Hours/Time)

Median ≈ 15.

Range 13–18 is common.

A couple of high outliers near 20.
👉 Most data tightly clustered around the center.

Middle-right (Miles 30,000–100,000)

Median ≈ 55,000.

IQR ≈ 45,000–65,000.

Many outliers above 80,000–100,000.
👉 Indicates a long right tail — some customers use extremely high miles.

Bottom-right (Miles 0–350)

Median ≈ 100.

IQR ≈ 50–150.

Several outliers above 200–350.
👉 Majority travel in shorter ranges, but a few travel much higher miles.

✅ Overall Insights

Usage variables: Mostly concentrated in the middle (2–5), with a few extreme users.

Miles: Highly skewed with many large outliers, meaning most users drive moderate distances but some travel exceptionally high.

Age,Education and Usage are having very few outliers.While income and miles are having more outliers.
"""

sns.violinplot(data=df, x='Usage', y='Miles', palette='ch:s=.25')
plt.xticks(rotation=15)   # rotate x-axis labels
plt.show()

sns.boxplot(data=df, x='MaritalStatus', y='Education', palette='ch:s=.25')
plt.xticks(rotation=15)   # rotate x-axis labels

sns.set_style(style='whitegrid')
fig, axs = plt.subplots(nrows=1, ncols=2, figsize=(15,6.5))

sns.countplot(data=df, x='Product', hue='Gender',
              edgecolor='0.15', ax=axs[0], palette="Set2")

sns.countplot(data=df, x='Product', hue='MaritalStatus',
              edgecolor='0.15', ax=axs[1], palette="husl")

axs[0].set_title('Product vs Gender', pad=10, fontsize=14)
axs[1].set_title('Product vs Marital Status', pad=10, fontsize=14)

axs[1].tick_params(axis='x', rotation=25)

plt.show()

"""##observation
Product vs Gender:

KP281 is equally popular among Male and Female.

KP481 is used by both genders almost equally, with males slightly higher.

KP781 is mostly chosen by Males, very few Females use it.

Product vs Marital Status:

Partnered customers dominate across all products.

KP281 is the top choice for Partnered users, followed by KP481.

KP781 has the lowest adoption, especially among Singles.

👉 Overall: KP281 is the most popular product, balanced by gender, but more strongly favored by Partnered customers. KP781 is the least popular, especially among Females and Singles.

"""

sns.boxplot(data=df, x='Product', y='Income',palette=["lightblue", "navy"]  , hue='Gender', width=0.7, whis=5, notch=False,showcaps=True)



sns.boxplot(data=df, x='Product', y='Income',palette=["lightblue", "pink"]  , hue='Gender', width=0.7, whis=5, notch=False,showcaps=True)

pd.crosstab(index=df.Product, columns=df.Gender, margins=True, normalize='index')

pd.crosstab(index=df.Product, columns=df.MaritalStatus, margins=True, normalize='index')

sns.boxplot(data=df, x="MaritalStatus", y="Miles", hue="Fitness", palette="ch:s=.25")

sns.boxplot(data=df, y="Education", x="Product", hue="Gender", palette="ch:s=.25")

attrs=['Age','Education','Fitness','Income','Usage','Miles']
sns.set_style('white')
fig, axs=plt.subplots(nrows=2,ncols=3, figsize=(15,5))
fig.subplots_adjust(top=1.1)
count=0
for i in range(2):
    for j in range(3):
        sns.boxplot(data=df, x='Product', y=attrs[count], orient='v', ax=axs[i,j], palette="ch:s=.25")
        count+=1
plt.show()

"""📊 Exploratory Data Analysis – Boxplot Insights

The following boxplots illustrate the relationship between customer attributes and product preference (KP281, KP481, KP781).

Key Observations

Age

KP281 and KP481 customers are younger (median age ~25).

KP781 customers are slightly older (median ~28–30) with higher variation.

Education

KP281 & KP481 users: education ~15–16 years.

KP781 users: higher education (~17–18 years).

Fitness

KP281 & KP481: concentrated around fitness score = 3.

KP781: higher scores (median ~4–5).

Income

KP281 & KP481: median income ~40k–50k.

KP781: significantly higher income (~75k–80k, max >100k).

Usage

KP281 & KP481: lower and stable usage.

KP781: higher usage frequency (median ~5).

Miles

KP281 & KP481: median miles ~80–100.

KP781: higher travel distance (median ~150–170, max >300).

📌 Insights

KP781 customers: older, better educated, fitness-conscious, higher income, frequent users, and travel longer distances.

KP281 & KP481 customers: younger, moderate income, lower usage, and shorter travel.

✅ Business Implication

KP781 → Premium product, target high-income & fitness-oriented professionals.

KP281 & KP481 → Affordable products, target younger customers and moderate-income groups.
"""